FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV production

# Install netcat (nc) for the health check we added to docker-compose
RUN apk add --no-cache netcat-openbsd

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app ./

EXPOSE 3002
CMD ["node", "index.js"]